name: cd-deploy

on:
  workflow_run:
    workflows: ["ci-push-artifact"] 
    types: [completed]
  workflow_dispatch: {}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (same commit as CI)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "test"

          # opcional: evita prompt de host authenticity
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST }}" >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Debug inventory files
        run: |
          pwd
          ls -la
          ls -la src/playbooks
          sed -n '1,120p' src/playbooks/invetory.ini


      - name: Deploy with Ansible
        env:
          BUILD_ID: ${{ github.event.workflow_run.head_sha }}
        run: |
          ARTIFACT_NAME="app-${BUILD_ID}.tar.gz"

          ansible-playbook \
            -i src/playbooks/invetory.ini \
            src/playbooks/deploy.yaml \
            --private-key ~/.ssh/id_rsa \
            -e "build_id=${BUILD_ID} artifact_name=${ARTIFACT_NAME}"
